### PR TITLE
Update TF 0.11.1 and aws provider to 1.5

### PR DESCRIPTION
**Pull request by helgi**

### CODE REVIEW

**Comment by knisbet** [comment]
retest this please

**Comment by knisbet** [comment]
Helgi, 

I think this is failing due to a change in terraform. 

> The command terraform apply with no explicit plan argument is now interactive by default. Specifically, it will show the generated plan and wait for confirmation before applying it, similar to the existing behavior of terraform destroy. The behavior is unchanged when a plan file argument is provided, and the previous behavior can be obtained without a plan file by using the -auto-approve option.

https://github.com/hashicorp/terraform/blob/master/CHANGELOG.md

The provisioner uses terraform apply here:
https://github.com/gravitational/provisioner/blob/82f7537aee0bc336a50151b18a26fe0050970392/scripts/Makefile#L217

**Comment by helgi** [comment]
@knisbet Yeah you are right, I added it for now but I'm not thrilled with the solution... But only other way is to provide it with a plan file... Wonder if we can use `input` in Jenkins in conjunction with the running plan first?

**Comment by knisbet** [comment]
retest this please

**Comment by knisbet** [comment]
retest this please

**Comment by knisbet** [comment]
@helgi If you rebase it should fix the latest CI failure. I made a mistake where I didn't bump the test application to the latest version when I upgraded the ops center to test a different fix (#26).

Also, I'm not sure I follow you about using input in jenkins. The way the jenkins CI tests work, is by basically simulating what a user would do, by building an application, uploading it to the ops center, and then requests the ops center to run provisioning. In this case, the terraform apply is triggered by make, which is the entry point for the provisioning container https://github.com/gravitational/provisioner/blob/c3e7c5befaac6e2adf9a01e8fe8056a69d0c45df/Dockerfile and isn't jenkins specific configuration.

**Comment by helgi** [comment]
I was mostly rubber ducking if we needed -input=false or not, was flying a
bit blind for a bit. I added it anyway in my last commit.

Will rebase in a little while. Thanks for tracking it down!

**Pull request merged**
